### ISSUE TITLE
Incorrect image on resource

### ISSUE THREAD

**Issue by jonwitts** [raspberrypilearning/getting-started-with-soldering#1]
Hi, 

This page: https://www.raspberrypi.org/learning/getting-started-with-soldering/components/soldering-iron/ should have an image on it but the link is broken. The page is linking here: https://www.raspberrypi.org/learning/images/components/soldering-iron.jpg (which is a 404) whereas I think it should be linking here: https://www.raspberrypi.org/learning/images/components/soldering-iron.png

I would have made the edit myself and put a pull request through, but I cannot find where that page is coming from in the repository!

Cheers,
Jon

**Comment by jonwitts** [comment]
OK... found the page in the repository. Pull request created.

**Comment by martinohanlon** [comment]
The component image is no longer used on the resource, so I am closing the issues but I have pulled your PR in as it was a bug, thanks.
